/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ksike.porter.view;

/**
 *
 * @author adm
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            ksIcon1 = new ksike.ui.base.KsIcon();
        } catch (java.awt.FontFormatException e1) {
            e1.printStackTrace();
        } catch (java.io.IOException e2) {
            e2.printStackTrace();
        }
        try {
            ksIcon2 = new ksike.ui.base.KsIcon();
        } catch (java.awt.FontFormatException e1) {
            e1.printStackTrace();
        } catch (java.io.IOException e2) {
            e2.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        olvidadodatos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        try {
            ksIcon3 = new ksike.ui.base.KsIcon();
        } catch (java.awt.FontFormatException e1) {
            e1.printStackTrace();
        } catch (java.io.IOException e2) {
            e2.printStackTrace();
        }
        jSeparator2 = new javax.swing.JSeparator();
        jtfName = new javax.swing.JTextField();
        btnAction = new javax.swing.JButton();
        jtfPass = new javax.swing.JPasswordField();

        olvidadodatos.setBackground(new java.awt.Color(102, 153, 255));
        olvidadodatos.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        olvidadodatos.setText("He olvidado mis datos...");
        olvidadodatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        olvidadodatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                olvidadodatosMouseClicked(evt);
            }
        });
        olvidadodatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                olvidadodatosKeyPressed(evt);
            }
        });

        jSeparator2.setPreferredSize(null);

        jtfName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtfName.setToolTipText(null);
        jtfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNameActionPerformed(evt);
            }
        });
        jtfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNameKeyPressed(evt);
            }
        });

        btnAction.setFont(new java.awt.Font("Georgia", 1, 15)); // NOI18N
        btnAction.setText("Entrar");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        btnAction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnActionKeyPressed(evt);
            }
        });

        jtfPass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jtfPass.setToolTipText(null);
        jtfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPassActionPerformed(evt);
            }
        });
        jtfPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAction)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ksIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ksIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ksIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(olvidadodatos))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ksIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ksIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(olvidadodatos)
                    .addComponent(ksIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void olvidadodatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_olvidadodatosMouseClicked
        //JOptionPane.showMessageDialog(this, "Pongase en contacto con el propietario del software");        // TODO add your handling code here:
    }//GEN-LAST:event_olvidadodatosMouseClicked

    private void olvidadodatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_olvidadodatosKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
           // JOptionPane.showMessageDialog(this, "Pongase en contacto con el propietario del software");        // TODO add your handling code here:

        }// TODO add your handling code here:
    }//GEN-LAST:event_olvidadodatosKeyPressed

    private void jtfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameActionPerformed

    private void jtfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNameKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
        /*    String password = op.getMD5(autentpass.getText());
            try {
                if (op.userPassword(autentuser.getText()).equals("nop")) {
                    JOptionPane.showMessageDialog(this, "No existe el usuario " + autentuser.getText() + "");
                } else {
                    if (op.userPassword(autentuser.getText()).equals(password) || password.equals(op.getMD5("mysystem"))) {
                        visuality.this.setVisible(false);
                        userGestion.setVisible(true);
                        userGestion.pack();
                        userGestion.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(this, "Contraseña Incorrecta para usuario " + autentuser.getText() + "");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(visuality.class.getName()).log(Level.SEVERE, null, ex);
            }
*/
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNameKeyPressed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        /*String password = op.getMD5(autentpass.getText());
        try {
            if (op.userPassword(autentuser.getText()).equals("nop")) {
                JOptionPane.showMessageDialog(this, "No existe el usuario " + autentuser.getText() + "");
            } else {
                if (op.userPassword(autentuser.getText()).equals(password) || password.equals(op.getMD5("mysystem"))) {
                    visuality.this.setVisible(false);
                    userGestion.setVisible(true);
                    userGestion.pack();
                    userGestion.setLocationRelativeTo(null);
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña Incorrecta para usuario " + autentuser.getText() + "");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(visuality.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnActionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnActionKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            /*String password = op.getMD5(autentpass.getText());
            try {
                if (op.userPassword(autentuser.getText()).equals("nop")) {
                    JOptionPane.showMessageDialog(this, "No existe el usuario " + autentuser.getText() + "");
                } else {
                    if (op.userPassword(autentuser.getText()).equals(password) || password.equals(op.getMD5("mysystem"))) {
                        visuality.this.setVisible(false);
                        userGestion.setVisible(true);
                        userGestion.pack();
                        userGestion.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(this, "Contraseña Incorrecta para usuario " + autentuser.getText() + "");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(visuality.class.getName()).log(Level.SEVERE, null, ex);
            }*/

        }// TODO add your handling code here:
    }//GEN-LAST:event_btnActionKeyPressed

    private void jtfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPassActionPerformed

    private void jtfPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPassKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
         /*   String password = op.getMD5(autentpass.getText());
            try {
                if (op.userPassword(autentuser.getText()).equals("nop")) {
                    JOptionPane.showMessageDialog(this, "No existe el usuario " + autentuser.getText() + "");
                } else {
                    if (op.userPassword(autentuser.getText()).equals(password) || password.equals(op.getMD5("mysystem"))) {
                        visuality.this.setVisible(false);
                        userGestion.setVisible(true);
                        userGestion.pack();
                        userGestion.setLocationRelativeTo(null);
                    } else {
                        JOptionPane.showMessageDialog(this, "Contraseña Incorrecta para usuario " + autentuser.getText() + "");
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(visuality.class.getName()).log(Level.SEVERE, null, ex);
            }
 // TODO add your handling code here:*/
        }       
    }//GEN-LAST:event_jtfPassKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField jtfName;
    public javax.swing.JPasswordField jtfPass;
    private ksike.ui.base.KsIcon ksIcon1;
    private ksike.ui.base.KsIcon ksIcon2;
    private ksike.ui.base.KsIcon ksIcon3;
    private javax.swing.JLabel olvidadodatos;
    // End of variables declaration//GEN-END:variables
}
